name: manual_build

on:
  workflow_dispatch:
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'What is the reason to trigger this manually?'
        # Default value if no value is explicitly provided
        default: 'testing github actions'
        # Input has to be provided for the workflow to run
        required: false

jobs:
  manual_build:
    name:  manual_build
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@master

    # install duckdb binary
      - name: Install DuckDB
        run: |
          wget https://github.com/duckdb/duckdb/releases/download/v1.2.1/duckdb_cli-linux-amd64.zip
          unzip duckdb_cli-linux-amd64
          rm duckdb_cli-linux-amd64.zip

    # run sql script with a specific token
      - name: Run SQL script
        env:
          MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
        run: ./duckdb < script.sql
