name: 'Scheduled Run'

on:
  schedule:
    - cron: '0 10 * * *'  # This line sets the job to run every day at 10am UTC

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@master

    # install duckdb binary
      - name: Install DuckDB
        run: |
          wget https://github.com/duckdb/duckdb/releases/download/v1.1.3/duckdb_cli-linux-amd64.zip
          unzip duckdb_cli-linux-amd64
          rm duckdb_cli-linux-amd64.zip

    # run sql script
      - name: Run SQL script
        run: ./duckdb > script.sql
